apiVersion: v2
name: dify
description: Dify deployment for home Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: dify
    version: 0.6.7
    repository: https://douban.github.io/charts