dify:
  global:
    storageClass: "local-path"
    
  api:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
  web:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
    
  worker:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
  redis:
    architecture: standalone
    auth:
      enabled: true
      password: "changeme-redis-password"
    master:
      persistence:
        enabled: true
        size: 5Gi
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
          
  postgresql:
    enabled: true
    auth:
      postgresPassword: "changeme-postgres-password"
      database: dify
    primary:
      persistence:
        enabled: true
        size: 10Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
          
  minio:
    auth:
      rootUser: minioadmin
      rootPassword: "changeme-minio-password"
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
        
  milvus:
    enabled: true
    standalone:
      persistence:
        enabled: true
        size: 10Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi