# Minimal Dify configuration for home-kubernetes
# External access via Cloudflared tunnel to dify.kotapiku.com

# Service configuration for Cloudflared tunnel
service:
  type: ClusterIP
  port: 80

# Disable ingress (using Cloudflared instead)
ingress:
  enabled: false

# Frontend configuration
frontend:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000

# API configuration  
api:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5001

# Worker configuration
worker:
  replicaCount: 1

# Minimal embedded dependencies
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

postgresql:
  enabled: true
  auth:
    postgresPassword: "difypassword"
    database: "dify"

# Disable optional components
sandbox:
  enabled: false

minio:
  enabled: false

# Use local storage instead of S3
global:
  storageType: "local"