apiVersion: batch/v1
kind: CronJob
metadata:
  name: kotatsu-news-cronjob
  namespace: kotatsu-news
spec:
  timeZone: 'Asia/Tokyo'
  schedule: "45 8 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kotatsu-news
            image: ghcr.io/amaotone/kotatsu-news:latest
            env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kotatsu-news-secret
                  key: SLACK_BOT_TOKEN
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: kotatsu-news-secret
                  key: SLACK_CHANNEL_ID
            - name: ANNIVERSARY_DATE
              valueFrom:
                secretKeyRef:
                  name: kotatsu-news-secret
                  key: ANNIVERSARY_DATE
            - name: OPEN_WEATHER_MAP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kotatsu-news-secret
                  key: OPEN_WEATHER_MAP_API_KEY
            - name: OPEN_WEATHER_MAP_ZIP
              valueFrom:
                secretKeyRef:
                  name: kotatsu-news-secret
                  key: OPEN_WEATHER_MAP_ZIP
          restartPolicy: OnFailure
