apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amaotone/home-kubernetes.git
    targetRevision: HEAD
    path: manifests/local-storage
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
