apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-livesync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amaotone/home-kubernetes.git
    targetRevision: HEAD
    path: manifests/obsidian-livesync
  destination:
    server: https://kubernetes.default.svc
    namespace: obsidian-livesync
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
