couchdb:
  clusterSize: 1
  persistentVolume:
    enabled: true 
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: local-storage
  couchdbConfig:
    couchdb:
      single_node: true
      uuid: obsidian-livesync
    chttpd:
      bind_address: any
      require_valid_user: true
    chttpd_auth:
      require_valid_user: true
      authentication_redirect: "/e=_/_utils/session.html"
    httpd:
      WWW-Authenticate: 'Basic realm="couchdb"'
      enable_cors: true
    cors:
      origins: app://obsidian.md,capacitor://localhost,http://localhost
      credentials: true
      headers: accept, authorization, content-type, origin, referer
      methods: GET, PUT, POST, HEAD, DELETE
      max_age: 3600
