---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCG6P6ZHoU3p29WFUohk/z9JoHGdaDQocCDeY06eZ0RL0UqsmSiU7lU1fSbgykNVOkpTDnQPOMnGhm5NGhYljdPmUjgyyeqJpjiUW6USFAcHSVm4iWlCNC8XVXDk/Kn9HCziduAiBE+zL2aY6XyuonAFwYoWwvaf5KHCk1Sjka/SOh7nSAFg1tR3Bg+3U/wTzIxjCUGk0e/1nfJd8rcgQy3gKhMg8WCYWyAe4hNeclgSyVoziFc+CI5axSOO3Dozy8yHiMijFvFkUdyZJpDck+HxZFMdOKtBUUEWM5b4eLJSckqin7xSigBE/lA6e5r5q9k1Svg2JOhC9A/KtUY+aVPzw1ngMkRnUTU7dw7Bicwc2WBD3jDaIJvE73EF/SSvlwuGfdxmNBwrrjuk4dCV2Se4JDZ2SPInayo5koslHnUhF9MN/YadIVzN4DUkJRvLJSkdNXORGf66057C80qFXwXjSX7/LgzauldYeaMsNi6b/zvjLrydiJyo65eKMmbxd9+FQvC8iX2f0g+P+xcSWmgrvoc+nnz6LNhS5ikdDefsWM9kvKInqx4z1SMrqBZyz8KroVZCgfoRWxXJuVzoho86SxGurIuKDLru4sParHqMlLk8FWnAVqzdrVtyZXzYDxJJ0V62ez69fkzAuH/QoBVKMmYADkAdl9CzDgkEUUIaZr8i5sV0s9j8etiBpLeNMuGtNUFtiUI5M6ARGSFfip871YD5O8s1temZbMBR9MLSG6pxeG1LERWTkPXhxhyXmGhpzMe0+t2VG2DL8QR6W6p/c8sfP2o7FEtBdOq22ilksAL4GErhU+TCGzSiq3YXXQvu4vTCdS0dn26ueJKo+0dmoGxoa7lzTztiqVrylZT1QnLoDQa4JtxEgz3ELBLVFezXqs5MkS2HMfrHaNdO10A6VJ1ONFfnyX0/hgB+vbpWtkQWR3VGWKz
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-token
      namespace: cloudflared
