---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret
  namespace: sealed-secrets
spec:
  encryptedData:
    CLOUDFLARE_TUNNEL_TOKEN: AgBlhvGAj2ztqu1sZjbBDfUca3pKgcd/3CBd5N1yb4R+vBu0QD+AXi9UjSqG6iRXTeHwLlqvX1NkkMs1NpzLdqoX0yTqO9iy02VDq0dGXu8PJgL4A2pwDUFAWXcLNcfJtgoXqrutrJPxTtjlJFM17cNitU0VXNOW2m3GYZXTapeqshrUYxyqg75pnU5r72FtVF7RkHvaX8TqdSkHcpmq/PsTBr3LxT3+gzWdnugCglyjLG4KZ4uRzgVG7BXWMXxRh5uaXHlUKem78t147hzPPbOiLmVJKOtUBm83RHgLkZ+E7xeHhKQRPNBlOmudBX9FMtAENfDbUe3qpJEAF2DHwJnGUHhO4RmAXJbxsodORqfzYIj3UEDaxRr4GWxSENSdwGNLXBoe5wdXueAXCiwQpRIj/I9vHdEzFWuyhsxJTPDJG+M/+9ltbS33idvLHYxFRLAz6K5LJ4YTIcS0er6dbtrSJ2nQQsZVaNmLRj+ck+FeHl0TIuZVPHRMDb8La8Z4R4qOcLbWMiH/UPCy0HkCtIKewU75l0AVheXr7DdUvqSC3bcqrb8Fk7kK270lymaQ6/WpHc99kkvIm125yAfiwKMCl+JXPIyMo2dH7pn2j9iv1Fs85wtrBfnATBgMSW8OLck2Df93tydB733AA/okGtWIYVQnKY7uHuxJbVJ1WSfEd9N0Zo259itQeGeWoy7yFe90yHu7deFsiGiLxW8Cd2F0C7AFf/WV2MKnHJbh07mmKvu3b/Tghc0FMGG5c7S8ZUASTfBtAq3yT8xTim2iWFZqHLDmmlaqOdbKGJJzLPqBVjdIddiEbvUohFwuEB31JYKqf3T/ymx+NfLWN8DJlPqFlWqbUP2AQVIf56j2wvP+nPc/EJdRSF1UzfNA5BHptTCo1TMFII8dYO2HBY4g6MK588naqWbnR8BacMFQC+DzC9gPygmoYBsG
  template:
    metadata:
      creationTimestamp: null
      name: secret
      namespace: sealed-secrets
