# This is a placeholder for the sealed secret
# Generate this using: echo -n "your-secret-key" | kubectl create secret generic n8n-secret --dry-run=client --from-literal=N8N_ENCRYPTION_KEY=replace-with-your-secret-key -o yaml | kubeseal -o yaml > n8n-sealed-secret.yaml

# For now, using a regular secret (should be replaced with SealedSecret in production)
apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: n8n-secret
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: replace-with-your-secret-key