apiVersion: v1
kind: Service
metadata:
  labels:
    service: postgres-n8n
  name: postgres
  namespace: n8n
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    service: postgres-n8n