# This is a placeholder for the sealed secret
# Generate this using: echo -n "your-secret-value" | kubectl create secret generic postgres-secret --dry-run=client --from-literal=POSTGRES_USER=changeUser --from-literal=POSTGRES_PASSWORD=change-me-in-production --from-literal=POSTGRES_DB=n8n --from-literal=POSTGRES_NON_ROOT_USER=n8n --from-literal=POSTGRES_NON_ROOT_PASSWORD=change-me-in-production -o yaml | kubeseal -o yaml > postgres-sealed-secret.yaml

# For now, using a regular secret (should be replaced with SealedSecret in production)
apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: change-me-in-production
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: n8n
  POSTGRES_NON_ROOT_PASSWORD: change-me-in-production