image:
  tag: "1.28.0"

service:
  type: ClusterIP
  annotations:
    external-dns.alpha.kubernetes.io/hostname: n8n.kotapiku.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

persistence:
  enabled: true
  size: 1Gi

ingress:
  enabled: false

main:
  config:
    n8n:
      host: "n8n.kotapiku.com"
      protocol: "https"
      port: "443"
      ssl_cert: "false"
      forwarded_headers: "true"
      trusted_proxies: "*"
      security_response_headers_enabled: "true"
      security_response_headers_content_security_policy: "upgrade-insecure-requests"
      security_response_headers_strict_transport_security: "max-age=31536000; includeSubDomains"
      secure_cookie: "true"
    db:
      type: "postgresdb"
      postgresdb:
        host: "postgresql.n8n.svc.cluster.local"
        database: "n8n"
        user: "n8n"
        port: "5432"
    timezone: "Asia/Tokyo"
  secret:
    db:
      postgresdb:
        password: "postgres-password"
    n8n:
      encryption_key: "change-me-to-secure-key"

extraManifests:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: postgresql-secret
      namespace: n8n
    type: Opaque
    stringData:
      POSTGRES_PASSWORD: "postgres-password"
      POSTGRES_USER: "n8n"
      POSTGRES_DB: "n8n"
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgresql
      namespace: n8n
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgresql
      template:
        metadata:
          labels:
            app: postgresql
        spec:
          containers:
            - name: postgresql
              image: postgres:14-alpine
              ports:
                - containerPort: 5432
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secret
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secret
                      key: POSTGRES_USER
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: postgresql-secret
                      key: POSTGRES_DB
              volumeMounts:
                - name: postgresql-data
                  mountPath: /var/lib/postgresql/data
                  subPath: postgres
          volumes:
            - name: postgresql-data
              persistentVolumeClaim:
                claimName: postgresql-pvc
  - apiVersion: v1
    kind: Service
    metadata:
      name: postgresql
      namespace: n8n
    spec:
      selector:
        app: postgresql
      ports:
        - port: 5432
          targetPort: 5432
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: postgresql-pvc
      namespace: n8n
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi 
