_shared_config:
  hostname: &hostname n8n.kotapiku.com
  url: &url https://n8n.kotapiku.com

image:
  repository: n8nio/n8n
  tag: "1.39.0"  # 特定のバージョンを指定

# 永続化設定 - n8nのデータ（アップロードファイル等）を保持
persistence:
  enabled: true
  type: dynamic  # 動的にPVCを作成
  accessModes:
    - ReadWriteOnce
  size: 10Gi  # アップロードファイル用に十分な容量を確保
  # mountPath: /home/node/.n8n  # デフォルトのマウントパス

main:
  # n8nの基本設定
  config:
    n8n:
      port: 5678
      protocol: http
      encryption_key: "replace-with-your-secret-key"  # 本番環境では必ず変更してください
      hide_usage_page: true
      editor_base_url: *url
      host: *hostname
    db:
      type: postgresdb
      postgresdb:
        host: postgres  # PostgreSQLサービス名
        port: 5432
        database: n8n
        user: n8n
    webhook_url: *url
    generic:
      timezone: "Asia/Tokyo"
  
  # セキュリティやデータベース接続情報などの機密情報
  # 本番環境ではSealedSecretsなどで暗号化してください
  secret:
    db:
      postgresdb:
        password: "change-me-in-production"  # 本番環境ではSealedSecretsなどで暗号化してください
  
  # Kubernetesリソース割り当て
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 512Mi
  
  
  # サービス設定
  service:
    type: ClusterIP
    port: 443
  
  # ポッドのセキュリティ設定
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  
  # アプリケーションのヘルスチェック
  livenessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
  
  readinessProbe:
    httpGet:
      path: /healthz
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10

# Ingressの設定
ingress:
  enabled: false
  # 必要に応じて有効化してください
  # className: "nginx"
  # annotations:
  #   cert-manager.io/cluster-issuer: "letsencrypt-prod"
  # hosts:
  #   - host: n8n.example.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  # tls:
  #   - secretName: n8n-tls
  #     hosts:
  #       - n8n.example.com

# ワーカーノード (スケーリング用)
worker:
  enabled: false

# Webhookノード (スケーリング用)
webhook:
  enabled: false

# Redis設定 (スケーリング時に必要)
valkey:
  enabled: false 
