image:
  tag: "1.28.0"

service:
  type: ClusterIP
  annotations:
    external-dns.alpha.kubernetes.io/hostname: n8n.kotapiku.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"

persistence:
  enabled: true
  size: 1Gi

env:
  - name: N8N_HOST
    value: "https://n8n.kotapiku.com"
  - name: NODE_ENV
    value: "production"
  - name: N8N_PROTOCOL
    value: "https"
  - name: WEBHOOK_TUNNEL_URL
    value: "https://n8n.kotapiku.com"
  - name: TZ
    value: "Asia/Tokyo"
  - name: N8N_SSL_CERT
    value: "false"
  - name: N8N_FORWARDED_HEADERS
    value: "true"
  - name: N8N_TRUSTED_PROXIES
    value: "*" 
