name: Build and Push kotatsu-news Image

on:
  push:
    branches:
      - main
    paths: 
      - "src/kotatsu-news/**"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/amaotone/kotatsu-news
          tags: |
            type=raw,value=latest
            type=sha,prefix=,suffix=,format=short
      
      - name: Push Image
        uses: docker/build-push-action@v5
        with:
          context: src/kotatsu-news
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
